use {
    crate::*,
    nom::{
        character::complete::line_ending, combinator::map, error::Error, multi::separated_list0,
        Err, IResult,
    },
    rayon::iter::{IntoParallelIterator, ParallelIterator},
    static_assertions::const_assert_eq,
    std::{collections::HashMap, hash::Hash, iter::from_fn},
};

/* --- Day 22: Monkey Market ---

As you're all teleported deep into the jungle, a monkey steals The Historians' device! You'll need to get it back while The Historians are looking for the Chief.

The monkey that stole the device seems willing to trade it, but only in exchange for an absurd number of bananas. Your only option is to buy bananas on the Monkey Exchange Market.

You aren't sure how the Monkey Exchange Market works, but one of The Historians senses trouble and comes over to help. Apparently, they've been studying these monkeys for a while and have deciphered their secrets.

Today, the Market is full of monkeys buying good hiding spots. Fortunately, because of the time you recently spent in this jungle, you know lots of good hiding spots you can sell! If you sell enough hiding spots, you should be able to get enough bananas to buy the device back.

On the Market, the buyers seem to use random prices, but their prices are actually only pseudorandom! If you know the secret of how they pick their prices, you can wait for the perfect time to sell.

The part about secrets is literal, the Historian explains. Each buyer produces a pseudorandom sequence of secret numbers where each secret is derived from the previous.

In particular, each buyer's secret number evolves into the next secret number in the sequence via the following process:

    Calculate the result of multiplying the secret number by 64. Then, mix this result into the secret number. Finally, prune the secret number.
    Calculate the result of dividing the secret number by 32. Round the result down to the nearest integer. Then, mix this result into the secret number. Finally, prune the secret number.
    Calculate the result of multiplying the secret number by 2048. Then, mix this result into the secret number. Finally, prune the secret number.

Each step of the above process involves mixing and pruning:

    To mix a value into the secret number, calculate the bitwise XOR of the given value and the secret number. Then, the secret number becomes the result of that operation. (If the secret number is 42 and you were to mix 15 into the secret number, the secret number would become 37.)
    To prune the secret number, calculate the value of the secret number modulo 16777216. Then, the secret number becomes the result of that operation. (If the secret number is 100000000 and you were to prune the secret number, the secret number would become 16113920.)

After this process completes, the buyer is left with the next secret number in the sequence. The buyer can repeat this process as many times as necessary to produce more secret numbers.

So, if a buyer had a secret number of 123, that buyer's next ten secret numbers would be:

15887950
16495136
527345
704524
1553684
12683156
11100544
12249484
7753432
5908254

Each buyer uses their own secret number when choosing their price, so it's important to be able to predict the sequence of secret numbers for each buyer. Fortunately, the Historian's research has uncovered the initial secret number of each buyer (your puzzle input). For example:

1
10
100
2024

This list describes the initial secret number of four different secret-hiding-spot-buyers on the Monkey Exchange Market. If you can simulate secret numbers from each buyer, you'll be able to predict all of their future prices.

In a single day, buyers each have time to generate 2000 new secret numbers. In this example, for each buyer, their initial secret number and the 2000th new secret number they would generate are:

1: 8685429
10: 4700978
100: 15273692
2024: 8667524

Adding up the 2000th new secret number for each buyer produces 37327623.

For each buyer, simulate the creation of 2000 new secret numbers. What is the sum of the 2000th secret number generated by each buyer?

--- Part Two ---

Of course, the secret numbers aren't the prices each buyer is offering! That would be ridiculous. Instead, the prices the buyer offers are just the ones digit of each of their secret numbers.

So, if a buyer starts with a secret number of 123, that buyer's first ten prices would be:

3 (from 123)
0 (from 15887950)
6 (from 16495136)
5 (etc.)
4
4
6
4
4
2

This price is the number of bananas that buyer is offering in exchange for your information about a new hiding spot. However, you still don't speak monkey, so you can't negotiate with the buyers directly. The Historian speaks a little, but not enough to negotiate; instead, he can ask another monkey to negotiate on your behalf.

Unfortunately, the monkey only knows how to decide when to sell by looking at the changes in price. Specifically, the monkey will only look for a specific sequence of four consecutive changes in price, then immediately sell when it sees that sequence.

So, if a buyer starts with a secret number of 123, that buyer's first ten secret numbers, prices, and the associated changes would be:

     123: 3
15887950: 0 (-3)
16495136: 6 (6)
  527345: 5 (-1)
  704524: 4 (-1)
 1553684: 4 (0)
12683156: 6 (2)
11100544: 4 (-2)
12249484: 4 (0)
 7753432: 2 (-2)

Note that the first price has no associated change because there was no previous price to compare it with.

In this short example, within just these first few prices, the highest price will be 6, so it would be nice to give the monkey instructions that would make it sell at that time. The first 6 occurs after only two changes, so there's no way to instruct the monkey to sell then, but the second 6 occurs after the changes -1,-1,0,2. So, if you gave the monkey that sequence of changes, it would wait until the first time it sees that sequence and then immediately sell your hiding spot information at the current price, winning you 6 bananas.

Each buyer only wants to buy one hiding spot, so after the hiding spot is sold, the monkey will move on to the next buyer. If the monkey never hears that sequence of price changes from a buyer, the monkey will never sell, and will instead just move on to the next buyer.

Worse, you can only give the monkey a single sequence of four price changes to look for. You can't change the sequence between buyers.

You're going to need as many bananas as possible, so you'll need to determine which sequence of four price changes will cause the monkey to get you the most bananas overall. Each buyer is going to generate 2000 secret numbers after their initial secret number, so, for each buyer, you'll have 2000 price changes in which your sequence can occur.

Suppose the initial secret number of each buyer is:

1
2
3
2024

There are many sequences of four price changes you could tell the monkey, but for these four buyers, the sequence that will get you the most bananas is -2,1,-1,3. Using that sequence, the monkey will make the following sales:

    For the buyer with an initial secret number of 1, changes -2,1,-1,3 first occur when the price is 7.
    For the buyer with initial secret 2, changes -2,1,-1,3 first occur when the price is 7.
    For the buyer with initial secret 3, the change sequence -2,1,-1,3 does not occur in the first 2000 changes.
    For the buyer starting with 2024, changes -2,1,-1,3 first occur when the price is 9.

So, by asking the monkey to sell the first time each buyer's prices go down 2, then up 1, then down 1, then up 3, you would get 23 (7 + 7 + 9) bananas!

Figure out the best sequence to tell the monkey so that by looking for that same sequence of changes in every buyer's future prices, you get the most bananas in total. What is the most bananas you can get? */

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
struct PriceChangeSequence([i8; Self::LEN]);

impl PriceChangeSequence {
    const LEN: usize = 4_usize;
    const LEN_MINUS_ONE: usize = Self::LEN - 1_usize;
    const PRICE_CHANGE_MIN: i8 = -9_i8;
    const PRICE_CHANGE_MAX: i8 = 9_i8;
    const PRICE_CHANGE_RANGE_LEN: u32 =
        (Self::PRICE_CHANGE_MAX - Self::PRICE_CHANGE_MIN + 1_i8) as u32;
    const COUNT: u32 = Self::PRICE_CHANGE_RANGE_LEN.pow(Self::LEN as u32);
}

impl From<u32> for PriceChangeSequence {
    fn from(mut value: u32) -> Self {
        let mut price_change_sequence: Self = Self::default();

        value %= Self::COUNT;

        for price_change in price_change_sequence.0.iter_mut() {
            *price_change = (value % Self::PRICE_CHANGE_RANGE_LEN) as i8 + Self::PRICE_CHANGE_MIN;
            value /= Self::PRICE_CHANGE_RANGE_LEN;
        }

        price_change_sequence
    }
}

type SecretNumberIndexRaw = u16;
type SecretNumberIndex = Index<SecretNumberIndexRaw>;
type PriceCache = HashMap<(PriceChangeSequence, SecretNumberIndex), i8>;

#[cfg_attr(test, derive(Debug, PartialEq))]
#[derive(Clone, Copy)]
struct SecretNumber(u32);

impl SecretNumber {
    fn evolve(mut self, evolutions: usize) -> Self {
        for _ in 0_usize..evolutions {
            const PRUNE_FACTOR: u32 = 16777216_u32;
            const PRUNE_FACTOR_U64: u64 = PRUNE_FACTOR as u64;
            const FACTOR_1: u32 = 64_u32;
            const FACTOR_1_BIT_SHIFT: u32 = FACTOR_1.trailing_zeros();
            const FACTOR_2: u32 = 32_u32;
            const FACTOR_2_BIT_SHIFT: u32 = FACTOR_2.trailing_zeros();
            const FACTOR_3: u32 = 2048_u32;
            const FACTOR_3_BIT_SHIFT: u32 = FACTOR_3.trailing_zeros();

            const_assert_eq!(FACTOR_1.count_ones(), 1_u32);
            const_assert_eq!(FACTOR_2.count_ones(), 1_u32);
            const_assert_eq!(FACTOR_3.count_ones(), 1_u32);

            self.0 = ((self.0 << FACTOR_1_BIT_SHIFT) ^ self.0) % PRUNE_FACTOR;
            self.0 = ((self.0 >> FACTOR_2_BIT_SHIFT) ^ self.0) % PRUNE_FACTOR;
            self.0 = ((((self.0 as u64) << FACTOR_3_BIT_SHIFT) ^ self.0 as u64) % PRUNE_FACTOR_U64)
                as u32;
        }

        self
    }

    fn price(self) -> i8 {
        (self.0 % 10_u32) as i8
    }

    fn iter_prices_and_changes(self) -> impl Iterator<Item = (i8, i8)> {
        let mut curr: Self = self;
        let mut curr_price: i8 = curr.price();

        from_fn(move || {
            let next: Self = curr.evolve(1_usize);
            let next_price: i8 = next.price();
            let price_change: i8 = next_price - curr_price;

            curr = next;
            curr_price = next_price;

            Some((curr_price, price_change))
        })
    }

    fn iter_prices_and_price_change_sequences(
        self,
    ) -> impl Iterator<Item = (i8, PriceChangeSequence)> {
        let mut price_change_sequence: PriceChangeSequence = PriceChangeSequence::default();

        self.iter_prices_and_changes()
            .map(move |(price, change)| {
                price_change_sequence.0.rotate_left(1_usize);
                price_change_sequence.0[PriceChangeSequence::LEN_MINUS_ONE] = change;

                (price, price_change_sequence)
            })
            .skip(PriceChangeSequence::LEN_MINUS_ONE)
    }

    fn populate_price_cache(
        self,
        index: SecretNumberIndex,
        evolutions: usize,
        price_cache: &mut PriceCache,
    ) {
        for (price, price_change_sequence) in self
            .iter_prices_and_price_change_sequences()
            .take(evolutions - PriceChangeSequence::LEN_MINUS_ONE)
        {
            let key: (PriceChangeSequence, SecretNumberIndex) = (price_change_sequence, index);

            if !price_cache.contains_key(&key) {
                price_cache.insert(key, price);
            }
        }
    }
}

impl Parse for SecretNumber {
    fn parse<'i>(input: &'i str) -> IResult<&'i str, Self> {
        map(parse_integer, Self)(input)
    }
}

#[cfg_attr(test, derive(Debug, PartialEq))]
pub struct Solution(Vec<SecretNumber>);

impl Solution {
    const EVOLUTIONS: usize = 2000_usize;

    fn secret_number_sum_after_evolutions(&self) -> u64 {
        self.0
            .iter()
            .map(|secret_number| secret_number.evolve(Self::EVOLUTIONS).0 as u64)
            .sum()
    }

    fn price_cache(&self) -> PriceCache {
        let mut price_cache: PriceCache = PriceCache::new();

        for (index, secret_number) in self.0.iter().enumerate() {
            secret_number.populate_price_cache(index.into(), Self::EVOLUTIONS, &mut price_cache);
        }

        price_cache
    }

    fn max_price_sum(&self) -> u32 {
        let price_cache: PriceCache = self.price_cache();

        (0_u32..PriceChangeSequence::COUNT)
            .into_par_iter()
            .map(|price_change_sequence| {
                let price_change_sequence: PriceChangeSequence = price_change_sequence.into();

                (0_usize..self.0.len())
                    .filter_map(|index| {
                        price_cache.get(&(price_change_sequence, SecretNumberIndex::from(index)))
                    })
                    .map(|&price| price as u32)
                    .sum()
            })
            .max()
            .unwrap_or_default()
    }
}

impl Parse for Solution {
    fn parse<'i>(input: &'i str) -> IResult<&'i str, Self> {
        map(separated_list0(line_ending, SecretNumber::parse), Self)(input)
    }
}

impl RunQuestions for Solution {
    /// Q1 this easy spells danger
    fn q1_internal(&mut self, _args: &QuestionArgs) {
        dbg!(self.secret_number_sum_after_evolutions());
    }

    /// When in doubt, cache.
    fn q2_internal(&mut self, _args: &QuestionArgs) {
        dbg!(self.max_price_sum());
    }
}

impl<'i> TryFrom<&'i str> for Solution {
    type Error = Err<Error<&'i str>>;

    fn try_from(input: &'i str) -> Result<Self, Self::Error> {
        Ok(Self::parse(input)?.1)
    }
}

#[cfg(test)]
mod tests {
    use {super::*, std::sync::OnceLock};

    const SOLUTION_STRS: &'static [&'static str] = &["1\n\
        10\n\
        100\n\
        2024\n"];

    fn solution(index: usize) -> &'static Solution {
        static ONCE_LOCK: OnceLock<Vec<Solution>> = OnceLock::new();

        &ONCE_LOCK.get_or_init(|| {
            vec![
                Solution(vec![
                    SecretNumber(1_u32),
                    SecretNumber(10_u32),
                    SecretNumber(100_u32),
                    SecretNumber(2024_u32),
                ]),
                Solution(vec![
                    SecretNumber(1_u32),
                    SecretNumber(2_u32),
                    SecretNumber(3_u32),
                    SecretNumber(2024_u32),
                ]),
            ]
        })[index]
    }

    #[test]
    fn test_try_from_str() {
        for (index, solution_str) in SOLUTION_STRS.iter().copied().enumerate() {
            assert_eq!(
                Solution::try_from(solution_str).as_ref(),
                Ok(solution(index))
            );
        }
    }

    #[test]
    fn test_evolve() {
        let secret_number: SecretNumber = SecretNumber(123_u32);

        for (evolutions, evolved_secret_number) in [
            SecretNumber(123_u32),
            SecretNumber(15887950),
            SecretNumber(16495136),
            SecretNumber(527345),
            SecretNumber(704524),
            SecretNumber(1553684),
            SecretNumber(12683156),
            SecretNumber(11100544),
            SecretNumber(12249484),
            SecretNumber(7753432),
            SecretNumber(5908254),
        ]
        .into_iter()
        .enumerate()
        {
            assert_eq!(secret_number.evolve(evolutions), evolved_secret_number);
        }

        for (index, secret_numbers) in [vec![
            SecretNumber(8685429_u32),
            SecretNumber(4700978_u32),
            SecretNumber(15273692_u32),
            SecretNumber(8667524_u32),
        ]]
        .into_iter()
        .enumerate()
        {
            for (secret_number, evolved_secret_number) in
                solution(index).0.iter().zip(secret_numbers)
            {
                assert_eq!(
                    secret_number.evolve(Solution::EVOLUTIONS),
                    evolved_secret_number
                );
            }
        }
    }

    #[test]
    fn test_secret_number_sum_after_evolutions() {
        for (index, secret_number_sum_after_evolutions) in [37327623_u64].into_iter().enumerate() {
            assert_eq!(
                solution(index).secret_number_sum_after_evolutions(),
                secret_number_sum_after_evolutions
            );
        }
    }

    #[test]
    fn test_iter_prices_and_changes() {
        assert_eq!(
            SecretNumber(123_u32)
                .iter_prices_and_changes()
                .take(9_usize)
                .collect::<Vec<(i8, i8)>>(),
            vec![
                (0_i8, -3_i8),
                (6_i8, 6_i8),
                (5_i8, -1_i8),
                (4_i8, -1_i8),
                (4_i8, 0_i8),
                (6_i8, 2_i8),
                (4_i8, -2_i8),
                (4_i8, 0_i8),
                (2_i8, -2_i8),
            ]
        );
    }

    #[test]
    fn test_price_sum_for_price_change_sequence() {
        let solution: &Solution = solution(1_usize);

        assert_eq!(solution.max_price_sum(), 23_u32);
    }

    #[test]
    fn test_input() {
        // let args: Args = Args::parse(module_path!()).unwrap().1;

        // Solution::both(&args);
    }
}
